media:
  input: src/media
  output: /media
content:
  - name: meta
    label: Meta
    type: file
    path: src/_data/meta.json
    fields:
      - name: title
        type: string
        label: Base Page Title
        description: All pages will have this at the end of the HTML title unless overridden
      - name: description
        type: string
        label: Site description
        description: Meta tag, comes up in google results and sometimes when sharing links
      - name: shareImage
        type: image
        label: Share Image
        description: Image shown in preview when sharing (e.g. whatsapp)