media:
  input: src/media
  output: /media
content:
  - name: meta
    label: Meta
    type: file
    path: src/_data/meta.json
    fields:
      - name: title
        type: string
        label: Base Page Title
        description: All pages will have this at the end of the HTML title unless overridden
      - name: description
        type: string
        label: Site description
        description: Meta tag, comes up in google results and sometimes when sharing links
      - name: shareImage
        type: image
        label: Share Image
        description: Image shown in preview when sharing (e.g. whatsapp)
      - name: event
        type: object
        label: Event
        fields:
          - name: show
            type: boolean
            label: Show Event
          - name: header
            type: string
            label: Header
          - name: secondHeader
            type: string
            label: Second Header
          - name: description
            type: rich-text
            label: Description
            options: { format: html }
          - name: date
            type: date
            label: Event Date
          - name: buttonText
            type: string
            label: Button Text
          - name: url
            type: string
            label: URL
      - name: testimonialsHeader
        type: string
        label: Testimonials Header
      - name: testimonials
        type: string
        list: true
        label: Testimonials
      - name: footerHeader
        type: string
        label: Footer Header
  - name: home
    label: Home
    type: file
    path: src/index.md
    fields:
      - name: layout
        hidden: true
        type: string
        default: home.ejs
      - name: title
        type: string
        label: Title
      - name: titleOverride
        type: string
        label: Title Override
        description: Full HTML title of the home page, ignores the meta config
      - name: heroImage
        type: image
        label: Hero Image
      - name: header
        type: string
        label: Header
      - name: introText
        type: rich-text
        options: { format: html }
        label: Intro Text
      - name: buttonText
        type: string
        label: Button Text
      - name: buttonUrl
        type: string
        label: Button URL
  - name: workshops
    label: Workshops
    type: file
    path: src/workshops.md
    fields:
      - name: layout
        hidden: true
        type: string
        default: workshops.ejs
      - name: titleOverride
        type: string
        label: Title Override
        default: "_IGNORE"
        hidden: true
      - name: title
        type: string
        label: Title
      - name: header
        type: string
        label: Header
      - name: introText
        type: rich-text
        options: { format: html }
        label: Intro Text
      - name: screwdriverText
        type: string
        label: Screwdriver Text
      - name: laptopText
        type: string
        label: Laptop Text
      - name: chipText
        type: string
        label: Chip Text
      - name: activitiesTitle
        type: string
        label: Activities Title
      - name: activities
        type: object
        list: true
        label: Activities
        fields:
          - name: header
            type: string
            label: Activity Header
          - name: image
            type: image
            label: Activity Image
          - name: imageAlt
            type: string
            label: Activity Image Alt Text
          - name: text
            type: rich-text
            options: { format: html }
            label: Activity Text
  - name: contact
    label: Contact
    type: file
    path: src/contact.md
    fields:
      - name: layout
        hidden: true
        type: string
        default: contact.ejs
      - name: titleOverride
        type: string
        label: Title Override
        default: "_IGNORE"
        hidden: true
      - name: title
        type: string
        label: Title
      - name: header
        type: string
        label: Header
      - name: introText
        type: rich-text
        options: { format: html }
        label: Intro Text
      - name: emailAddress
        type: string
        label: Email Address
      - name: phoneNumber
        type: string
        label: Phone Number
  - name: about
    label: About
    type: file
    path: src/about.md
    fields:
      - name: layout
        hidden: true
        type: string
        default: about.ejs
      - name: titleOverride
        type: string
        label: Title Override
        default: "_IGNORE"
        hidden: true
      - name: title
        type: string
        label: Title
      - name: header
        type: string
        label: Header
      - name: image
        type: image
        label: Image
      - name: imageAlt
        type: string
        label: Image Alt Text
      - name: text
        type: rich-text
        options: { format: html }
        label: Text
